/**
 * dank-trank plugin example
 *
 * This file demonstrates how to extend dank-trank with custom detectors and generators.
 * Place this file as `dank-trank.config.js` in your project root.
 *
 * Usage:
 *   - Custom detectors: return a DetectionResult or null from detect()
 *   - Custom generators: return a GeneratedFile or null from generate()
 */

/** @type {import('dank-trank').DankTrankConfig} */
export default {
  // --------------------------------------------------------
  // Custom detector: detects a hypothetical "Rails" stack
  // --------------------------------------------------------
  detectors: [
    {
      name: 'rails-detector',
      async detect(rootDir) {
        const { existsSync } = await import('node:fs');
        const { join } = await import('node:path');

        if (!existsSync(join(rootDir, 'Gemfile'))) return null;
        const gemfile = (await import('node:fs/promises')).readFileSync(
          join(rootDir, 'Gemfile'),
          'utf-8',
        );
        if (!gemfile.includes('rails')) return null;

        return {
          // NOTE: 'django' is used here for demo purposes since 'rails' is not a
          // built-in StackType. In a real plugin you would augment the type system.
          stack: 'django',
          confidence: 90,
          details: { framework: 'Rails', language: 'Ruby' },
          databases: [],
        };
      },
    },
  ],

  // --------------------------------------------------------
  // Custom generator: adds a fly.io fly.toml config
  // --------------------------------------------------------
  generators: [
    {
      name: 'flyio-generator',
      async generate(ctx) {
        // Only run if user sets ctx.flyio = true (e.g. via a CLI flag or your own wizard)
        if (!ctx.flyio) return null;

        const content = `# fly.io configuration — generated by dank-trank plugin-example
app = "${ctx.projectName}"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[[services]]
  http_checks = []
  internal_port = ${ctx.port}
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
`;

        return {
          relativePath: 'fly.toml',
          content,
          description: 'fly.io deployment configuration',
        };
      },
    },
  ],
};
